config/routes.rb
# encoding: utf-8
#
# Redmine plugin to export an issue as a .eml file
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

RedmineApp::Application.routes.draw do
  
  # issue to email settings creation and administration
  resources :projects do #project
    member do #project_names
      scope 'settings' do #only for settings
        resources :issue_to_email_settings, :param => :issue_to_email_setting_id #all necessary routes
      end
    end
  end
  
  match "issue_to_email_test_imap" => "issue_to_email_settings#test_imap", :as => "issue_to_email_test_imap", :via => [:post, :put]
  
  match "issues/:id/store" => "issues#store", :as => "issue_to_email_store", :via => [:get]
  match "issues/store"     => "issues#bulk_store", :as => "issue_to_email_bulk_store", :via => [:post]
  
end

app/views/projects/settings/issue_to_email/_edit.html.erb
<%= form_for @issue_to_email_setting, {:url =>  issue_to_email_setting_path(@project, @issue_to_email_setting),
									 :method => :put,
									 :html => {:id => "issue_to_email_setting-form" }
									 } do |f| %>
<%= render :partial => '/projects/settings/issue_to_email/form', :locals => {:f => f }  %>
<%- end #form_for %>

app/views/projects/settings/issue_to_email/_form.html.erb
<div class="box">
  <%= error_messages_for 'issue_to_email_setting' %>

  <div class="splitcontentleft">
	<h3><%= l(:label_issue_to_email_settings_imap_server_settings) %></h3>
	<%= render :partial => 'projects/settings/issue_to_email/server_settings', :locals => {f: f, issue_to_email_setting: @issue_to_email_setting} %>
	<%= render :partial => 'projects/settings/issue_to_email/status_after', :locals => {f: f, issue_to_email_setting: @issue_to_email_setting} %>
  </div>

  <div class="splitcontentright">
	<h3><%= l(:label_issue_to_email_settings_server_script_settings) %></h3>
	<%= render :partial => 'projects/settings/issue_to_email/script_settings', :locals => {f: f, issue_to_email_setting: @issue_to_email_setting}  %>
  </div>

  <div style="clear:both;"></div>

  <%= f.submit l(:label_save), :name => 'save' %> 


	<div class="contextual">
	  <%-if @issue_to_email_setting.id %>
		<%= link_to l(:button_delete),
					{ controller: 'issue_to_email_settings', action: 'destroy', issue_to_email_setting_id: @issue_to_email_setting.id, project_id: @project.id, tab: 'issue_to_email_settings' },
					data: { confirm: l(:text_are_you_sure)}, method: 'delete', class: 'icon icon-del' %>
	  <%- end %>
	</div>
  <div style="clear:both;">&nbsp;</div>
</div>

app/views/projects/settings/issue_to_email/_script_settings.html.erb
<fieldset class="box tabular">
<legend><%= l(:label_issue_to_email_settings_server_script) %></legend>

  <%= labelled_fields_for :issue_to_email_setting, issue_to_email_setting do |setting_fields| %>
    <p><%= setting_fields.text_area :server_script, :value => issue_to_email_setting.server_script %>
	  <a class='icon icon-help' href='#' title='<%= "#{l(:label_help)}" %>' onclick='$("#help_issue_to_email_server_script").toggle(); return false;'><%= l(:label_help) %></a>
	  <br>
	  <span id="help_issue_to_email_server_script" class="info" style="display: none;">
		<em class="info"><%= l(:label_example_issue_to_email_server_script).html_safe %></em>
	  </span>
    </p>
  <%- end # labelled_fields_for %>

</fieldset>

app/views/projects/settings/issue_to_email/_server_settings.html.erb
<fieldset class="box tabular">
<legend><%= l(:label_issue_to_email_settings_imap_server) %></legend>
  <script type="text/javascript" charset="utf-8">
    function changeIssueToEmailServerSettings(element) {

      if (element.value == 'imap') {
        $('#issue_to_email_server_settings').show();
        $('#issue_to_email_imap_settings').show();
        $('#issue_to_email_host_settings').show();
      }

      if (element.value == '') {
        $('#issue_to_email_server_settings').hide();
        $('#issue_to_email_imap_settings').hide();
        $('#issue_to_email_host_settings').hide();
      }
    }
  </script>
  <%= labelled_fields_for :issue_to_email_setting, issue_to_email_setting do |setting_fields| %>
  
	<p><%= setting_fields.select(:protocol, options_for_select([['', ""], ["imap", "imap"]], issue_to_email_setting.protocol), {}, {:onchange => "changeIssueToEmailServerSettings(this)"} ) %></p>

	<div id="issue_to_email_server_settings" <%= issue_to_email_setting.protocol.blank? ? "style='display: none;'".html_safe : ''  %>>

	  <p><%= setting_fields.text_field :host, :value => issue_to_email_setting.host %></p>
	  <p><%= setting_fields.text_field :port, :value => issue_to_email_setting.port %></p>
	  <p><%= setting_fields.text_field :username, :value => issue_to_email_setting.username %></p>

	  <p>
		<%= content_tag 'label', l(:field_password), :id => "issue_to_email_password_label", :style => (issue_to_email_setting.username.blank? ? 'display:none;' : nil ) %>
		<%= link_to_function( image_tag('edit.png'), '$("#issue_to_email_password_label").hide(); $(this).hide(); $("#issue_to_email_password_field").show()' ) unless issue_to_email_setting.username.blank? %>
		<%= content_tag 'span', :id => "issue_to_email_password_field", :style => (issue_to_email_setting.username.blank? ? nil : 'display:none;') do %>
		  <%= setting_fields.password_field :password, :value => issue_to_email_setting.password %>
		<% end %>
	  </p>

	  <p><%= setting_fields.check_box :use_ssl %></p>
	  <p><%= setting_fields.check_box :ssl_verify %></p>
	
	  <span id="issue_to_email_imap_settings" <%= issue_to_email_setting.protocol != 'imap' ? "style='display: none;'".html_safe : ''  %> >
		<p><%= setting_fields.text_field :imap_folder, :value => issue_to_email_setting.imap_folder %></p>
	  </span>

    <span id="issue_to_email_test_connectivity">
	  <p> 
		<label class="icon icon-email">
		  <%= link_to l(:label_issue_to_email_test_connectivity), "#",
					  :remote => true,
					  :onclick => "issueToEmailJsForm('#{issue_to_email_test_imap_path(:feedback_message_area => 'issue_to_email_test_connectivity', :project_id => @project.id)}',  $('#issue_to_email_setting-form'))",
					  :class => "" %> 
	    </label>
	  </p>
	  <div id="issue_to_email_test_connectivity"></div>

	  <%= javascript_include_tag "issue_to_email", :plugin => "redmine_issue_to_email" %>

    </span> <!-- test connectivity -->
	 
	</div> <!-- Server settings -->
	
	<input type="hidden" name="id" value="<%= params[:id] %>">
	<input type="hidden" name="issue_to_email_setting_id" value="<%= params[:issue_to_email_setting_id] %>">
	<input type="hidden" name="tab" value="issue_to_email_settings">
		
  <%- end # labelled_fields_for %>

</fieldset>

app/views/projects/settings/issue_to_email/_status_after.html.erb
<%= labelled_fields_for :issue_to_email_setting, issue_to_email_setting do |setting_fields| %>
  <fieldset class="box tabular"><legend><%= l(:label_issue_to_email_status_after) %> </legend>
    <p>
      <%= setting_fields.select(:status_id, ("<option value=\"\">#{l(:label_issue_to_email_no_change_option)}</option>" + options_for_select(IssueStatus.all.collect {|p| [p.name, p.id.to_s]}, issue_to_email_setting[:status_id])).html_safe) %>
    </p>
  </fieldset>
<%- end %>